apiVersion: apps/v1
kind: Deployment
metadata:
  name: shape-analyzer
  labels:
    app: shape-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shape-analyzer
  template:
    metadata:
      labels:
        app: shape-analyzer
    spec:
      nodeName: 10.0.88.201
      securityContext:
        fsGroup: 2000
      containers:
      - name: shape-analyzer
        image: shape-analyse:v2
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: FLASK_ENV
          value: "production"
        - name: MAX_CONTENT_LENGTH
          value: "16777216"  # 16MB
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
        securityContext:
          runAsUser: 1000
          runAsGroup: 2000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 20
          periodSeconds: 20
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 5000
          failureThreshold: 30
          periodSeconds: 10
      volumes:
      - name: uploads
        emptyDir:
          medium: Memory
          sizeLimit: "100Mi" 