apiVersion: apps/v1
kind: Deployment
metadata:
  name: shape-analyzer
  labels:
    app: shape-analyzer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shape-analyzer
  template:
    metadata:
      labels:
        app: shape-analyzer
    spec:
      nodeName: 10.0.88.201
      containers:
      - name: shape-analyzer
        image: shape-analyse:v1
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "512Mi"
            cpu: "500m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        volumeMounts:
        - name: uploads
          mountPath: /app/uploads
      volumes:
      - name: uploads
        emptyDir: {} 