apiVersion: v1
kind: Service
metadata:
  name: shape-analyzer-service
spec:
  selector:
    app: shape-analyzer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 35000
  type: NodePort 